import pymongo,csv,sys

coll = "ebird_top10_2008_2012"
in_f = sys.argv[1]
out_f = sys.argv[2]

client = pymongo.MongoClient()
db = client.creeval
birds = db[coll]

fields = [u'YEAR', u'TIME', u'ELEV_NED', u'CAUS_SNOW12', u'CAUS_SNOW10', u'CAUS_SNOW11', u'DIST_FROM_FLOWING_FRESH', u'LONGITUDE', u'CAUS_TEMP_AVG03', u'CAUS_TEMP_AVG02', u'CAUS_TEMP_AVG01', u'CAUS_TEMP_AVG07', u'CAUS_TEMP_AVG06', u'CAUS_TEMP_AVG05', u'CAUS_TEMP_AVG04', u'CAUS_TEMP_AVG09', u'CAUS_TEMP_AVG08', u'DIST_FROM_WET_VEG_BRACKISH', u'DIST_FROM_STANDING_BRACKISH', u'HOUSING_PERCENT_VACANT', u'DIST_FROM_WET_VEG_FRESH',  u'CAUS_TEMP_AVG10', u'CAUS_TEMP_AVG11', u'CAUS_TEMP_AVG12', u'CAUS_TEMP_AVG13', u'DIST_FROM_STANDING_FRESH', u'CAUS_TEMP_MAX09', u'CAUS_TEMP_MAX08', u'CAUS_TEMP_MAX01', u'CAUS_TEMP_MAX03', u'CAUS_TEMP_MAX02', u'CAUS_TEMP_MAX05', u'CAUS_TEMP_MAX04', u'CAUS_TEMP_MAX07', u'CAUS_TEMP_MAX06', u'CAUS_PREC11', u'CAUS_TEMP_MIN', u'CAUS_TEMP_MAX', u'CAUS_TEMP_MAX12', u'CAUS_TEMP_MAX13', u'CAUS_TEMP_MAX10', u'CAUS_TEMP_MAX11', u'UMD2011_LANDCOVER',  u'CAUS_LAST_SPRING_32F_MEAN', u'CAUS_PREC', u'CAUS_PREC10', u'CAUS_PREC13', u'CAUS_PREC12', u'CAUS_SNOW', u'ASTER2011_DEM', u'_id', u'CAUS_TEMP_AVG', u'CAUS_PREC08', u'CAUS_PREC09', u'CAUS_PREC02', u'CAUS_PREC03', u'CAUS_PREC01', u'CAUS_PREC06', u'CAUS_PREC07', u'CAUS_PREC04', u'CAUS_PREC05', u'CAUS_FIRST_AUTUMN_32F_MEAN', u'POP00_SQMI', u'Turdus_migratorius', u'DIST_FROM_FLOWING_BRACKISH', u'CAUS_LAST_SPRING_32F_MEDIAN', u'CAUS_LAST_SPRING_32F_EXTREME', u'CAUS_TEMP_MIN07', u'CAUS_TEMP_MIN06', u'CAUS_TEMP_MIN05', u'CAUS_TEMP_MIN04', u'CAUS_TEMP_MIN03', u'CAUS_TEMP_MIN02', u'CAUS_TEMP_MIN01', u'CAUS_TEMP_MIN09', u'CAUS_TEMP_MIN08', u'DAY', u'ELEV_GT', u'CAUS_FIRST_AUTUMN_32F_MEDIAN', u'CAUS_FIRST_AUTUMN_32F_EXTREME', u'HOUSING_DENSITY', u'CAUS_SNOW01', u'CAUS_SNOW03', u'CAUS_SNOW02', u'CAUS_TEMP_MIN10', u'CAUS_TEMP_MIN11', u'CAUS_TEMP_MIN12', u'CAUS_TEMP_MIN13', u'LATITUDE', u'CAUS_SNOW04']

with open(out_f,"w") as o:
	writer = csv.DictWriter(o,fieldnames=fields, extrasaction="ignore")
	writer.writeheader()
	with open(in_f,"r") as f:
		reader = csv.reader(f)
		for row in reader:
			bird_id = reader.next()[0]
			writer.writerow(birds.find_one({"_id":bird_id}))
